# Generated by Django 5.1.1 on 2024-09-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_taskcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.taskcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default='Applications', on_delete=django.db.models.deletion.CASCADE, to='main.creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='category',
            field=models.CharField(choices=[('Applications', 'Applications'), ('Networking', 'Networking'), ('Projects', 'Projects'), ('Meetings', 'Meetings'), ('Certifications', 'Certifications')], max_length=50),
        ),
    ]
